from typing import Protocol, runtime_checkable


@runtime_checkable
class LoggerProtocol(Protocol):
    def debug(self, msg: str, *args: object, **kwargs: object) -> None: ...
    def info(self, msg: str, *args: object, **kwargs: object) -> None: ...
    def warning(self, msg: str, *args: object, **kwargs: object) -> None: ...
    def error(self, msg: str, *args: object, **kwargs: object) -> None: ...
    def critical(self, msg: str, *args: object, **kwargs: object) -> None: ...
